Feature/sc 3367 upload image directory
Superb-AI-Suite/superb-ai-curate-python pull request #54
Opened 2024-08-07 14:04 UTC by jhkim1215

## Change description

## Test & Review

2024-08-08 02:10 UTC, jhkim1215 commented on spb_curate/curate/api/curate.py
> +                    if len(image_key) > 255:
If i were to move this elsewhere as a const, where to?

2024-08-08 07:41 UTC, cosseyluke requested changes
Have added some comments.

2024-08-08 07:41 UTC, cosseyluke commented on spb_curate/curate/api/curate.py
> +    def upload_image_directory(
```suggestion
    def upload_images_from_directory(
```

2024-08-08 07:41 UTC, cosseyluke commented on spb_curate/curate/api/curate.py
> +    _supported_image_extensions = [
This should be a dict, not a list for faster lookups. You could consider using `SupportedImageFormat.__members__`.

2024-08-08 07:41 UTC, cosseyluke commented on spb_curate/curate/api/settings.py
> +MAX_IMAGE_KEY_LENGTH = 255
Keep this alphabetically ordered please.

2024-08-08 07:41 UTC, cosseyluke commented on spb_curate/curate/api/curate.py
> +                    if len(image_key) > settings.MAX_IMAGE_KEY_LENGTH:
I think we should consider a `force` parameter that clips the `image_key` to `settings.MAX_IMAGE_KEY_LENGTH` instead of throwing a validation error.

2024-08-09 06:23 UTC, jhkim1215 commented on spb_curate/curate/api/curate.py
> +                    if len(image_key) > settings.MAX_IMAGE_KEY_LENGTH:
we will consider adding it later since it does alert the user before uploading anything, the user can fix it themselves.

2024-08-09 07:25 UTC, cosseyluke approved these changes
Nice work

2024-08-12 05:37 UTC, merged